version: '3.7'

services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    enviroment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=gestify
    volumes:
      - gestify_pg_data:/bitnami/postgresql


